name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - stable
      - feature*

jobs:
  standard:
    strategy:
      fail-fast: false
      matrix:
        python:
        - 3.7

    name: "Python ${{ matrix.python }}"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create Docker Image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          tags: clif:latest
          build-args: |
              PYTHON_VERSION=${{ matrix.python }}
              
    - name: Build
      run: docker run clif:latest ls
